name: Brand Name Check

on:
  push:
    branches:
      - '*'
      
jobs:
  branch_name_check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check branch name
        run: |
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          if [[ "$branch_name" == feature/* ]]; then
            echo "Branch name is valid."
          else
            echo "Invalid branch name. It should start with 'feature/'."
            exit 1
          fi
    
    
