name: Brand Name Check

on:
  push:
    branches:
      - '*'
      
jobs:
  branch_name_check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check branch name
        run: |
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          
          prefix=$(echo "$branch_name" | cut -d'/' -f1)
          lowercase_prefix=$(echo "$prefix" | tr '[:upper:]' '[:lower:]')

          if [[ "$branch_name" == */* && "$lowercase_prefix" == "feature" ]]; then
            if [[ "$branch_name" == "Feature" ]]; then
              echo "Feature/ is invalid"
              exit 1
            else
              echo "Branch name is valid"
